// Code generated by protoc-gen-go. DO NOT EDIT.
// source: studytrack.proto

package studytrack

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3e258921f26d8, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3e258921f26d8, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Subject struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deadline             int64    `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3e258921f26d8, []int{2}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Subject) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Subject) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

type CreateSubjectRequest struct {
	Subject              *Subject `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubjectRequest) Reset()         { *m = CreateSubjectRequest{} }
func (m *CreateSubjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubjectRequest) ProtoMessage()    {}
func (*CreateSubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3e258921f26d8, []int{3}
}

func (m *CreateSubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubjectRequest.Unmarshal(m, b)
}
func (m *CreateSubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubjectRequest.Merge(m, src)
}
func (m *CreateSubjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubjectRequest.Size(m)
}
func (m *CreateSubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubjectRequest proto.InternalMessageInfo

func (m *CreateSubjectRequest) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*Subject)(nil), "Subject")
	proto.RegisterType((*CreateSubjectRequest)(nil), "CreateSubjectRequest")
}

func init() { proto.RegisterFile("studytrack.proto", fileDescriptor_06b3e258921f26d8) }

var fileDescriptor_06b3e258921f26d8 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0xe9, 0xfc, 0x9f, 0x3b, 0x1f, 0x1f, 0x4e, 0x18, 0x99, 0x5a, 0x14, 0x4a, 0x56, 0x5d,
	0xa5, 0x58, 0x77, 0xc5, 0x9d, 0x1b, 0xc1, 0x5d, 0x07, 0x37, 0x82, 0x8b, 0x4c, 0x7b, 0x19, 0xa2,
	0xb5, 0xa9, 0x49, 0x3a, 0xe0, 0xd6, 0x57, 0xf0, 0xd1, 0x7c, 0x05, 0x1f, 0x44, 0x9a, 0xb4, 0x45,
	0xd0, 0x5d, 0xee, 0xbd, 0x87, 0x73, 0x7e, 0x87, 0xc0, 0x89, 0x36, 0x4d, 0xf1, 0x66, 0x14, 0xcf,
	0x9f, 0x59, 0xad, 0xa4, 0x91, 0xc1, 0xf9, 0x41, 0xca, 0x43, 0x89, 0x31, 0xaf, 0x45, 0xcc, 0xab,
	0x4a, 0x1a, 0x6e, 0x84, 0xac, 0xb4, 0xbb, 0xd2, 0x00, 0x26, 0xf7, 0x1a, 0x15, 0x21, 0x30, 0xa9,
	0xf8, 0x0b, 0xfa, 0xa3, 0xd0, 0x8b, 0x96, 0x99, 0x7d, 0x53, 0x06, 0xeb, 0x1b, 0x85, 0xdc, 0x60,
	0xab, 0xc8, 0xf0, 0xb5, 0x41, 0x6d, 0xc8, 0x19, 0x4c, 0x1a, 0x8d, 0xca, 0xf7, 0x42, 0x2f, 0x5a,
	0x25, 0x53, 0x66, 0x6f, 0x76, 0x45, 0x1f, 0x61, 0xbe, 0x6b, 0xf6, 0x4f, 0x98, 0x1b, 0xb2, 0x81,
	0xa9, 0x11, 0xa6, 0x44, 0x2b, 0x5b, 0x66, 0x6e, 0x20, 0x21, 0xac, 0x0a, 0xd4, 0xb9, 0x12, 0x75,
	0x8b, 0xd0, 0x65, 0xfd, 0x5c, 0x91, 0x00, 0x16, 0x05, 0xf2, 0xa2, 0x14, 0x15, 0xfa, 0xe3, 0xd0,
	0x8b, 0xc6, 0xd9, 0x30, 0xd3, 0x14, 0x36, 0x0e, 0xa7, 0x0b, 0xe9, 0x89, 0x28, 0xcc, 0xb5, 0xdb,
	0x74, 0x50, 0x0b, 0xd6, 0x2b, 0xfa, 0x43, 0x72, 0x07, 0xab, 0x16, 0x74, 0x87, 0xea, 0x28, 0x72,
	0x24, 0xd7, 0x30, 0x73, 0x56, 0x84, 0xb0, 0x5f, 0x15, 0x03, 0x57, 0x8a, 0x6e, 0xdf, 0x3f, 0xbf,
	0x3e, 0x46, 0x6b, 0xba, 0x8c, 0x8f, 0x97, 0x71, 0x5b, 0x50, 0xa7, 0xb6, 0x67, 0xf2, 0x00, 0xff,
	0xbb, 0x80, 0xde, 0xef, 0x76, 0xf0, 0x3b, 0x65, 0x7f, 0x31, 0x06, 0x03, 0x12, 0xbd, 0xb0, 0xae,
	0x5b, 0xfa, 0xaf, 0x75, 0xed, 0xf0, 0x74, 0xda, 0x83, 0xee, 0x67, 0xf6, 0x5b, 0xae, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xa2, 0x02, 0xa5, 0xed, 0xc8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *CreateUserRequest) (*User, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studytrack.proto",
}

// SubjectServiceClient is the client API for SubjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubjectServiceClient interface {
	Create(ctx context.Context, in *CreateSubjectRequest, opts ...grpc.CallOption) (*Subject, error)
}

type subjectServiceClient struct {
	cc *grpc.ClientConn
}

func NewSubjectServiceClient(cc *grpc.ClientConn) SubjectServiceClient {
	return &subjectServiceClient{cc}
}

func (c *subjectServiceClient) Create(ctx context.Context, in *CreateSubjectRequest, opts ...grpc.CallOption) (*Subject, error) {
	out := new(Subject)
	err := c.cc.Invoke(ctx, "/SubjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubjectServiceServer is the server API for SubjectService service.
type SubjectServiceServer interface {
	Create(context.Context, *CreateSubjectRequest) (*Subject, error)
}

// UnimplementedSubjectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSubjectServiceServer struct {
}

func (*UnimplementedSubjectServiceServer) Create(ctx context.Context, req *CreateSubjectRequest) (*Subject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSubjectServiceServer(s *grpc.Server, srv SubjectServiceServer) {
	s.RegisterService(&_SubjectService_serviceDesc, srv)
}

func _SubjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SubjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectServiceServer).Create(ctx, req.(*CreateSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SubjectService",
	HandlerType: (*SubjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SubjectService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studytrack.proto",
}
