// Code generated by protoc-gen-go. DO NOT EDIT.
// source: studytrack.proto

package studytrack

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3e258921f26d8, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3e258921f26d8, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateSubjectRequest struct {
	Subject              *Subject `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubjectRequest) Reset()         { *m = CreateSubjectRequest{} }
func (m *CreateSubjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubjectRequest) ProtoMessage()    {}
func (*CreateSubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3e258921f26d8, []int{2}
}

func (m *CreateSubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubjectRequest.Unmarshal(m, b)
}
func (m *CreateSubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubjectRequest.Merge(m, src)
}
func (m *CreateSubjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubjectRequest.Size(m)
}
func (m *CreateSubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubjectRequest proto.InternalMessageInfo

func (m *CreateSubjectRequest) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "studytrack.CreateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "studytrack.GetUserRequest")
	proto.RegisterType((*CreateSubjectRequest)(nil), "studytrack.CreateSubjectRequest")
}

func init() { proto.RegisterFile("studytrack.proto", fileDescriptor_06b3e258921f26d8) }

var fileDescriptor_06b3e258921f26d8 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4f, 0x4a, 0xf3, 0x40,
	0x14, 0x27, 0xdf, 0x57, 0x22, 0x7d, 0xc5, 0xb4, 0x8e, 0x11, 0x64, 0x50, 0x28, 0x43, 0x17, 0x6e,
	0x6c, 0x20, 0xae, 0xec, 0x56, 0xa4, 0xe0, 0x46, 0x68, 0x71, 0xe5, 0x6a, 0x1a, 0x1f, 0x25, 0x6a,
	0x33, 0x75, 0xe6, 0x45, 0x10, 0x71, 0xe3, 0x15, 0xbc, 0x85, 0xd7, 0xf1, 0x0a, 0x1e, 0x44, 0x32,
	0xc9, 0xe8, 0x94, 0x74, 0x17, 0x5e, 0x7e, 0xff, 0x07, 0x06, 0x86, 0xca, 0xbb, 0x17, 0xd2, 0x32,
	0x7b, 0x18, 0xaf, 0xb5, 0x22, 0xc5, 0xe0, 0xef, 0xc2, 0x8f, 0x96, 0x4a, 0x2d, 0x1f, 0x31, 0x91,
	0xeb, 0x3c, 0x91, 0x45, 0xa1, 0x48, 0x52, 0xae, 0x0a, 0x53, 0x23, 0x79, 0x5f, 0xa3, 0x51, 0xa5,
	0xce, 0xb0, 0x39, 0x88, 0x73, 0xd8, 0xbb, 0xd0, 0x28, 0x09, 0x6f, 0x0c, 0xea, 0x19, 0x3e, 0x95,
	0x68, 0x88, 0x8d, 0xa0, 0x53, 0x1a, 0xd4, 0x87, 0xc1, 0x30, 0x38, 0xe9, 0xa5, 0x83, 0xb1, 0x67,
	0x68, 0x61, 0xf6, 0xaf, 0x18, 0x41, 0x34, 0x45, 0xf2, 0x79, 0x0c, 0x3a, 0x85, 0x5c, 0xa1, 0xe5,
	0x75, 0x67, 0xf6, 0x5b, 0x5c, 0x42, 0x5c, 0x1b, 0xcc, 0xcb, 0xc5, 0x3d, 0x66, 0xe4, 0xb0, 0xa7,
	0xb0, 0x63, 0xea, 0x4b, 0x63, 0xb3, 0xef, 0xdb, 0x38, 0xb0, 0xc3, 0xa4, 0x9f, 0x01, 0xf4, 0x2a,
	0xab, 0x39, 0xea, 0xe7, 0x3c, 0x43, 0x76, 0x0d, 0x61, 0x2d, 0xcb, 0x8e, 0x7d, 0x5e, 0xab, 0x0b,
	0x6f, 0xa5, 0x17, 0xf1, 0xfb, 0xd7, 0xf7, 0xc7, 0xbf, 0x48, 0x84, 0x49, 0x55, 0xc3, 0x4c, 0x6c,
	0x1b, 0x76, 0x05, 0xff, 0xa7, 0x48, 0x8c, 0xfb, 0xf0, 0xcd, 0x7a, 0x5b, 0xa4, 0x0e, 0xac, 0x54,
	0x9f, 0xed, 0xd6, 0x52, 0xc9, 0x6b, 0x55, 0xf9, 0x2d, 0x5d, 0x41, 0xd4, 0x14, 0x70, 0x71, 0x6f,
	0x7f, 0xe3, 0x0e, 0xdb, 0x71, 0x37, 0x97, 0xe1, 0xdb, 0x86, 0x10, 0xdc, 0x3a, 0xc5, 0xa2, 0x9b,
	0x34, 0x8b, 0x98, 0x89, 0xdb, 0x66, 0x11, 0xda, 0xa7, 0x3c, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x99, 0x4f, 0x16, 0x49, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	Get(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/studytrack.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/studytrack.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *CreateUserRequest) (*User, error)
	Get(context.Context, *GetUserRequest) (*User, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) Get(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/studytrack.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/studytrack.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "studytrack.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studytrack.proto",
}

// SubjectServiceClient is the client API for SubjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubjectServiceClient interface {
	Create(ctx context.Context, in *CreateSubjectRequest, opts ...grpc.CallOption) (*Subject, error)
}

type subjectServiceClient struct {
	cc *grpc.ClientConn
}

func NewSubjectServiceClient(cc *grpc.ClientConn) SubjectServiceClient {
	return &subjectServiceClient{cc}
}

func (c *subjectServiceClient) Create(ctx context.Context, in *CreateSubjectRequest, opts ...grpc.CallOption) (*Subject, error) {
	out := new(Subject)
	err := c.cc.Invoke(ctx, "/studytrack.SubjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubjectServiceServer is the server API for SubjectService service.
type SubjectServiceServer interface {
	Create(context.Context, *CreateSubjectRequest) (*Subject, error)
}

// UnimplementedSubjectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSubjectServiceServer struct {
}

func (*UnimplementedSubjectServiceServer) Create(ctx context.Context, req *CreateSubjectRequest) (*Subject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSubjectServiceServer(s *grpc.Server, srv SubjectServiceServer) {
	s.RegisterService(&_SubjectService_serviceDesc, srv)
}

func _SubjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/studytrack.SubjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectServiceServer).Create(ctx, req.(*CreateSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "studytrack.SubjectService",
	HandlerType: (*SubjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SubjectService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studytrack.proto",
}
