// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resources.proto

package studytrack

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Subject struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{1}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Subject) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Subject) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

type Theme struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Theme) Reset()         { *m = Theme{} }
func (m *Theme) String() string { return proto.CompactTextString(m) }
func (*Theme) ProtoMessage()    {}
func (*Theme) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{2}
}

func (m *Theme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Theme.Unmarshal(m, b)
}
func (m *Theme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Theme.Marshal(b, m, deterministic)
}
func (m *Theme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Theme.Merge(m, src)
}
func (m *Theme) XXX_Size() int {
	return xxx_messageInfo_Theme.Size(m)
}
func (m *Theme) XXX_DiscardUnknown() {
	xxx_messageInfo_Theme.DiscardUnknown(m)
}

var xxx_messageInfo_Theme proto.InternalMessageInfo

func (m *Theme) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "studytrack.Student")
	proto.RegisterType((*Subject)(nil), "studytrack.Subject")
	proto.RegisterType((*Theme)(nil), "studytrack.Theme")
}

func init() { proto.RegisterFile("resources.proto", fileDescriptor_cf1b13971fe4c19d) }

var fileDescriptor_cf1b13971fe4c19d = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4e, 0x85, 0x30,
	0x10, 0x40, 0x83, 0x8a, 0xe8, 0xb0, 0x30, 0x69, 0x5c, 0x10, 0x8c, 0x91, 0xb0, 0x62, 0x55, 0x12,
	0x4d, 0x3c, 0x08, 0x70, 0x81, 0xd2, 0x8e, 0x58, 0xa5, 0x2d, 0x69, 0xa7, 0x0b, 0x6e, 0x6f, 0x52,
	0x82, 0xf9, 0x8b, 0xbf, 0x9b, 0x99, 0xf7, 0x26, 0x79, 0xf0, 0xe4, 0x31, 0xb8, 0xe8, 0x25, 0x06,
	0xbe, 0x79, 0x47, 0x8e, 0x41, 0xa0, 0xa8, 0x76, 0xf2, 0x42, 0xfe, 0xd6, 0x6f, 0x8b, 0x73, 0xcb,
	0x8a, 0x7d, 0x22, 0x73, 0xfc, 0xea, 0x49, 0x1b, 0x0c, 0x24, 0xcc, 0x76, 0xc8, 0xed, 0x2b, 0x14,
	0x23, 0x45, 0x85, 0x96, 0x18, 0x83, 0x3b, 0x2b, 0x0c, 0x56, 0x59, 0x93, 0x75, 0x8f, 0x43, 0x9a,
	0xdb, 0x1d, 0x8a, 0x31, 0xce, 0x3f, 0x28, 0x89, 0x3d, 0x43, 0x4e, 0x9a, 0xd6, 0x93, 0x1f, 0x0b,
	0x6b, 0xa0, 0x54, 0x18, 0xa4, 0xd7, 0x1b, 0x69, 0x67, 0xab, 0x9b, 0xc4, 0x2e, 0x4f, 0xec, 0x13,
	0x1e, 0x14, 0x0a, 0xb5, 0x6a, 0x8b, 0xd5, 0x6d, 0x93, 0x75, 0xe5, 0x7b, 0xcd, 0x8f, 0x2a, 0x7e,
	0x56, 0xf1, 0xe9, 0xac, 0x1a, 0xfe, 0xdd, 0xf6, 0x05, 0xf2, 0xe9, 0x1b, 0x0d, 0x5e, 0xeb, 0x9a,
	0xef, 0xd3, 0xeb, 0xc7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xdc, 0xb0, 0x66, 0xfd, 0x00,
	0x00, 0x00,
}
